version: "3.7"

services:
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 80:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=password
    pgsql:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
